//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web.Services.Description;

namespace WebTraining.Models.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album
    {
        public Album()
        {
            this.Tracks = new HashSet<Track>();
        }
    

        public int AlbumId { get; set; }

        [RegularExpression(@"[ A-Za-z0-9._% +-] +@[ A-Za-z0-9.-] +\.[ A-Za-z]{ 2,4}",ErrorMessage = "Invalid Email")]
        public string Title { get; set; }

         [Required]
        [Range(1,100)]

        public int ArtistId { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual ICollection<Track> Tracks { get; set; }
    }
}
